### ISSUE TITLE
Add ability to prevent `BrowserRouter` reload until static content loaded

### ISSUE THREAD

**Issue by arctic-hen7** [sycamore-rs/sycamore#182]
I'm using Sycamore in an SSR project at the moment, and it would be extremely helpful if the `BrowserRouter` logic could have some function by which the reload could be prevented until some static HTML has been fetched from a server. As far as I understand Sycamore, I don't think there's a way to block the rendering of the new `template!` without also blocking the main UI thread. I've tried rendering the content in a `div` outside the scope of the `BrowserRouter`, but then all links simply reload the whole page, as I assume functions like `navigate` need the `BrowserRouter` to be their parent.

I'm not entirely sure how this would be implemented, but it'd allow the prevention of a white flash or the need for `Loading...` text. More broadly, this would allow the implementation of custom loading bars say at the tops of pages as on YouTube and other sites, which I don't believe is currently possible with Sycamore.

My other consideration was implementing my own small version of `BrowserRouter` for this use-case, though I believe the route matching logic is a private function. If the above task is too much for now, making this function public would be greatly appreciated!

**Comment by lukechu10** [comment]
Do you mean something like Next.js's [`getServerSideProps`](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering) or SvelteKit's [`load`](https://kit.svelte.dev/docs#loading) hook?

I plan to have something similar for `sycamore-router` and if you have some design ideas, I'll be happy to hear them.

Right now, my idea is to have a `#[preload(|| { /* data-fetching logic here */})]` tag on routes that will run once on the server for the initial request and on the client for subsequent navigation (or always on the client in SPA mode). The data returned by the function could be put into a special prop on the enum variant, maybe called `data` or other (this is the part that I don't like as much. It feels kind of like a hack and the new name restriction feels somewhat arbitrary).

It would also be nice to have a `prefetch` attribute on links so that hovering them will run the `preload` function before the actual click.

As for now, you can use the [`Route::match_route`](https://docs.rs/sycamore-router/0.5.2/sycamore_router/trait.Route.html#tymethod.match_route) method that should be automatically derived by the `Route` proc-macro.

**Comment by arctic-hen7** [comment]
That design sounds fantastic! More generally though, it'd be really great to be able to just suspend the reload of the existing content in the `BrowserRouter` until some action has been performed. Right now, I don't think there's any way for example to have a custom loading bar after the user clicks a link, any interim before the page is ready is just a white flash (because a template must be returned).

Thank you very much for the `match_route` function, I did not realize that was public!

**Comment by lukechu10** [comment]
New docs for router preloading here: https://sycamore-rs.netlify.app/docs/advanced/routing#data-fetching-and-preloading
