### ISSUE TITLE
Bind value causes rust-analyzer to report error

### ISSUE THREAD

**Issue by dwarn-axiallon** [sycamore-rs/sycamore#199]
**Describe the bug**
When I add an input(bind:value=some_signal) to my template rust-analyzer complains with the following error message "this operation is unsafe and requires an unsafe function or block". The application still builds and runs successfully but the template is highlighted in red as if there an error. I am using VS Code as my IDE.

**To Reproduce**
Add an input(bind:value=some_signal) to a template in VS Code with the rust-analyzer plugin loaded.

**Expected behavior**
Expecting no error to be displayed.

**Environment**
- Visual Studio Code: 1.58.2
- rust-analyzer: 0.2.694
- Sycamore: 0.5.2

**Comment by lukechu10** [comment]
The reason for that is because rust-analyzer does not expand attribute proc-macros by default.
You see this error because we rely on js bindings that look something like
```rust
#[wasm_bindgen]
extern "C" {
    pub fn my_function();
}
```
Rust by default makes `extern "C"` functions `unsafe` because they are generally used for FFI which causes this error.

If you want, you can enable `rust-analyzer.experimental.procAttrMacros` which should resolve the error. Note that it's still experimental and some features don't work yet (notably code completion inside functions with attributes).

**Comment by dwarn-axiallon** [comment]
Enabling `rust-analyzer.experimental.procAttrMacros` resolved the issue. Thank you so much!
