### ISSUE TITLE
'Ergonomic and intuitive' is arguable

### ISSUE THREAD

**Issue by adsick** [sycamore-rs/sycamore#207]
mb I'm just dumb, but looking at sycamore for the first time does not makes an impression that it is simple or natural. 

it is not even Rust, but a bunch of macro magic.
that's an opinion.

**Comment by adsick** [comment]
and btw I like the whole concept of writing entire web apps in Rust, but it should be done in a clear and pleasing manner. 

maybe MoonZoon will deliver that, who knows.

**Comment by lukechu10** [comment]
> it is not even Rust, but a bunch of macro magic.

Well sycamore's macros are actually quite simple and I do plan on introducing a builder syntax in the future as well. Also macros are part of Rust so I don't believe that's incorrect.

As you said, "ergonomic and intuitive" is an opinion and of course not everybody will like it. In fact, every framework or library will have some kind of claim that is arguable. I personally believe that Sycamore is quite natural but you can disagree.

Since this issue is not constructive, I will be closing this. If you have a more specific complaint about Sycamore, please open a new issue.

**Comment by adsick** [comment]
Of course you can do what you want, but... ye.

note what Cart said about using macros (in Bevy engine development):
"Macro-free ergonomics. In Bevy we have an aversion to macros because they are DSLs (domain specific languages). We want to write Rust, not "custom language we invented that happens to live inside Rust..."

link: https://bevyengine.org/news/bevys-first-birthday/#bevy-ecs
