### ISSUE TITLE
JSX-like syntax macro

### ISSUE THREAD

**Issue by stoically** [sycamore-rs/sycamore#23]
Nice work on maple! Really like the VDOM-free reactivity approach and looking forward to see how this develops.

Wanted to leave a shameless plug here: in case you'd ever consider a JSX-like syntax for maple, then maybe my [syn-rsx](https://crates.io/crates/syn-rsx) crate might be of interest.

Feel free to close the issue if you consider this out of scope or an ad :D, and good luck with the library!

**Comment by lukechu10** [comment]
Thanks for the feedback. Although I don't plan on supporting JSX anytime soon, I could see why some would prefer a JSX-like syntax (more familiar to React developers for one thing).

Personally, I am not to big a fan of JSX. It is a bit too verbose for my taste. I actually really like [Pug](https://pugjs.org/api/getting-started.html) but it relies on indentation for nesting which wouldn't work inside a proc-macro. In fact, the current `template!` macro is inspired form Pug syntax.

I'll leave this open as this could be a possibility in the future and I'll keep your crate in mind if I ever implement this :)

**Comment by ufoscout** [comment]
Hi @lukechu10 
I really like the sycamore philosophy, anyway, I think that the syntax chosen for the template library reduces the userbase considerably. In fact, the standard HTML or HTML-like syntax is extremely familiar to everyone and it would definitely attract more people.
For example, when choosing a web framework for a project, in my team, we immediately discard every option that uses a custom template syntax because we don't want and we don't feel the need for learning something different.

**Comment by lukechu10** [comment]
@ufoscout that's a good point. I think we could have something like [Marko's precise syntax](https://markojs.com/docs/concise/). The only thing I don't like about this is that it adds maintenance burden because now we need to maintain two codegens. Perhaps there could be a shared codegen "backend" and multiple codegen "frontends" (maybe even one with a builder-like syntax?).

**Comment by pythoneer** [comment]
To add to the confusion: What i value most is easy integration into my development environment. I absolutely don't care if its JSX(-like) or any other syntax. Its easy to learn anyway and anything i came across (from other frameworks etc.) is manageable to use in a few minutes, so personally i don't see a problem here other than "taste" and in my case i can swallow that pill in exchange of a good experience. And what i mean with "good experience" is: can my development environment handle it to assist me with e.g. code completion, syntax checks, code formatting etc. 
And in the current scope Macros as particular bad at serving in that regard. If 60% of my code base consists of that is a blackbox to my development environment because it is wrapped inside a Macros this is really not helpful. I used yew quite a bit that has a JSX(-like) syntax and it can really getting frustrating. At least the current Syntax can be handled to some extend by `rustfmt` and that is a relieve. I am really not happy to manually indent markup. Saying that i wouldn't be angry about a builder like way to describe the template even if i need to write more code after all. This "disadvantage" gets easily balanced out with code completion that also serves as a "discoverability" tool, too. Code completion helps discover an API and macro syntax is especially hard to discover. 

I have yet to see a good solution in the Rust space to handle this because unfortunately every attempt at this turned out to be overly verbose, making it unpractical. So my conclusion is: i am not happy with the Macro approach anyway in terms of compatibility with assistant tools (code completion etc) and the current Macros is equally bad as JSX despite it works with `rustfmt` to some extend which is a plus over JSX that fails miserably (as it works in other projects/frameworks). So if the rust tooling (macro syntax inspection, code completion etc.) does not improve – personally – i don't see a point in JSX or any other syntax different from the current one. The only improvement i see currently is to come up with a good way to have a "vanilla" builder like pattern that provides code completion, syntax checking and formatting that might get obsolete if the rust toolset improves to have the same experience with DSL's like the current macros or the proposed JSX(-like) one and until that day i don't see how JSX can improve the current situation. For me personally its just more work for very little benefit.

**Comment by lukechu10** [comment]
@pythoneer that's a good point. I think the only way to have good IDE completion (at least for the foreseeable future) is to introduce a builder syntax. Something like: https://github.com/hamza1311/yew-dsl for Sycamore would be nice.

**Comment by ufoscout** [comment]
Do you think something like Angular `templateUrl` would be feasible in rust?

I mean, in Angular you can have the HTML template code in a dedicated file so you get automatic HTML code completion/formatting/linting/etc.

For example, in `src/components/myComponent.html`:
```html
<div>Hello from MyComponent<div>
```

and in `src/components/myComponent.ts`:
```typescript
@Component({
  templateUrl: './myComponent.html',
})
export class MyComponent { }
```

Maybe we could have in Sycamore something like this?
```rust
#[component(MyComponent<G>)]
fn my_component(value: StateHandle<i32>) -> Template<G> {
    templateUrl! { "./myComponent.html" }
}
```

**Comment by pythoneer** [comment]
@ufoscout what about `std::include_str`?

**Comment by lukechu10** [comment]
> Do you think something like Angular `templateUrl` would be feasible in rust?

That would definitely be possible with a proc-macro. The only problem would be lack for code completion for rust inside the html file.

**Comment by ctjhoa** [comment]
The builder API is now released https://github.com/sycamore-rs/sycamore/pull/269

**Comment by Ahidada** [comment]
I have a simple idea, can you make a plug-in, so that the editing effect in the IDE is like " markdown " as the WYSIWYG, only need to show the right side of the " view! " html" code on the right side, lol.

**Comment by davidon-top** [comment]
There is [sycamore-rstml](https://github.com/davidon-top/sycamore-rstml) (made by me) that is an alternative view macro, unfortunately i cant publish it yet because it relies on sycamore git rather then from crates.io for now you can depend on the git tag

**Comment by lukechu10** [comment]
Another consideration is that I would eventually like to have a `sycamorefmt` utility and it would be nice to have it support rstml as well.

**Comment by davidon-top** [comment]
this issue can proboably be closed now since after the next sycamore-view-parser release [this](https://github.com/sycamore-community/sycamore-rstml) will be published on crates.io

**Comment by lukechu10** [comment]
> this issue can proboably be closed now since after the next sycamore-view-parser release [this](https://github.com/sycamore-community/sycamore-rstml) will be published on crates.io

Awesome! This is actually the oldest open issue on this repo!
