### ISSUE TITLE
Rename `Template` to `View`

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#266]
The current name `Template` is a bit misleading. `View` sounds better and also makes the macro name shorter (`view!` instead of `template!`.

This is a major breaking change but since we're still at 0.x, we can do it. To ease migration, we can define a type alias with `#[deprecated(...)]` to prevent code from breaking while emitting a warning.

In most cases, migration should simply be performing a find and replace for `Template` with `View`.

**Comment by jquesada2016** [comment]
Do you think `view` is the best option? Just curious because it makes it sound a bit more like an MVC pattern, which Sycamore isn't really. `html` might also work.

I'm not against it, I like `view` much more than `template`, but since the name will change, might as well consider it! :)

**Comment by arctic-hen7** [comment]
This would also make usage with Perseus *much* less confusing, because Perseus also has its own concept of templates. I'm all for this!

**Comment by lukechu10** [comment]
> `html` might also work.

I'm a bit hesitant with `html` because I want to eventually support non HTML backends (e.g. something like React Native). Other potential alternatives to consider:
- `node`
- `rsx`
- `ui`
- `tree`

**Comment by arctic-hen7** [comment]
Here are my opinions on these:

- `node` -- feels a little misleading because it can store many HTMl 'nodes'
- `rsx` -- this will make people from the JS ecosystem expect HTML syntax, as with JSX, so it might be better to avoid
- `ui` -- nice
- `tree` -- maybe, but you can have multiple top-level elements, and this term might be better kept for referring to more technical parts of the infrastructure

Personally, I'd be happy with `View` or `Ui`, with perhaps a preference for the first.

**Comment by lukechu10** [comment]
View it is then. This will be changed for 0.7.0

**Comment by arctic-hen7** [comment]
Fantastic! Thanks so much, this will be great for the usability of Perseus!
