### ISSUE TITLE
Make `KeyedProps`/`IndexedProps` usable with more iterable types

### ISSUE THREAD

**Issue by AMNRG** [sycamore-rs/sycamore#318]
Currently `KeyedProps` and `IndexedProps` is limited to `Vec`.
Maybe we can extend the restriction to anything that implements the `Iterator` trait.

**Comment by lukechu10** [comment]
I think I've changed my mind on this issue. Implementing this feature would make the already messy generics on `Indexed` and `Keyed` much worse. It would also put a small performance penalty on `Vec` since we now need to do an extra clone to keep the implementation generic.

Using a non `Vec` type is actually quite simple, just add a `.into_iter().collect::<Vec<_>>()` and that's it!

I think this also makes it more clear as to what exactly we are iterating over.
