### ISSUE TITLE
Remove opaque type from `ElementBuilder`

### ISSUE THREAD

**Issue by goiw111** [sycamore-rs/sycamore#466]
**Describe the bug**
opaque type error

![Screenshot from 2022-08-12 03-25-23](https://user-images.githubusercontent.com/32710356/184274545-4eeaef67-67dd-437a-b5e6-b768b82c2547.png)

![Screenshot from 2022-08-12 03-25-52](https://user-images.githubusercontent.com/32710356/184274071-a91c11f4-d839-4a3c-adda-d80b433c49d6.png)

help, please

**Environment**

- sycamore = "0.8.0-beta.7"
- Browser: Chrome
- OS: Fedora

**Comment by lukechu10** [comment]
Ah that won't really work because the builder relies on opaque functions behind the hood and each builder function returns a different opaque type. That means that the type of `section().class("Accordion")` is different from `s.t("11")` and therefore causes a type error.

A simple way to fix this would be to change the initial value to something like `section().class("Accordion").t("")` so that the types are the same. However, it is usually more idiomatic to map the iterator instead of folding it, i.e.
```rust
section().class("Accordion").c(
    View::new_fragment(props.iter.iter().map(|i| t("11")).collect())
)
```
Or just use `Indexed`/`Keyed`.

**Comment by goiw111** [comment]
why do you don't make ElementBuilder like this 
pub struct ElementBuilder<'a, G: GenericNode>(
    Box<dyn FnOnce(Scope<'a>) -> G>
    PhantomData<&'a ()>,
);

**Comment by lukechu10** [comment]
> why do you don't make ElementBuilder like this pub struct ElementBuilder<'a, G: GenericNode>( Box<dyn FnOnce(Scope<'a>) -> G> PhantomData<&'a ()>, );

It makes it much harder for the compiler to optimize the function calls. This means that it will result in an allocation for every method call of the builder. I haven't measured the performance impact, but it will likely make the builder quite a bit slower than the `view!` macro.

**Comment by goiw111** [comment]
I made some changes and now its works for me
https://github.com/sycamore-rs/sycamore/commit/80cd29eb2f37958adb37021d7a9a43f132a3746b

can you make some tests for the performance, please

**Comment by lukechu10** [comment]
> can you make some tests for the performance, please

I'll try to get to it but I'm quite busy at the moment so it might take a while. I'll keep this issue open to track this.

**Comment by jquesada2016** [comment]
One of the difficulties I'm having with the opaque type, is that it is somewhat unintuitive on how to go about conditionally adding classes, children, etc. from the props. For example:
```rust
let mut el = if props.el == "div" { div() } else { a() };

if let Some(class_name) = props.some_class {
  el = el.class(class_name);
}
```

The above wouldn't compile because there's no way to reconcile the types due to the opaqueness.

My workaround is to just use the `dyn` and `dyn_if` methods to try and achieve what I need.

**Comment by jquesada2016** [comment]
I do agree with having a declarative builder API, but there needs to be more builder methods to support this, at minimum a builder method which takes in `Option` for all respective kinds, such as `option_class`, `option_on`, etc., otherwise there is no real way to construct an element if you need any kind of branching logic, which is extremely common when building the low level reusable core components to a design system.

The `on` method, for example, requires that you add an event listener to the node regardless if the user wants it or not, causing a small, but cascading performance impact on lower end devices. For example, take the following highly reused component:

```rust
#[derive(Prop)]
pub struct Props<'a, G> {
  on_click: Option<Box<dyn Fn(G::EventType) + 'a>>
}

#[component]
pub fn HighlyReused<G: Html>(cx: Scope, props: Props) -> View<G> {
  button()
    .on("click", move |e| {
      if let Some(on_click) = props.on_click {
        on_click(e)
      }
    })
}
```

That is the only feasible way to currently conditionally attach an "optional" event listener, even though it will actually attach an event listener, even if one is not desired.

If you think it's worth it, I can write up an RFC describing the methods that can be added to cover most use cases. and you can let me know what you think!
