### ISSUE TITLE
Hydration mismatch between Router and StaticRouter

### ISSUE THREAD

**Issue by duarten** [sycamore-rs/sycamore#469]
**Describe the bug**

On master (2bb51c3b5a4cef21d4d1b0e6757096b3a2b5e08b), hydration fails when trying to match html generated from a `Router` to html generated from a `StaticRouter`.

**To Reproduce**

Consider the following code:

```rust
#[derive(Route, Clone)]
pub enum AppRoutes {
    #[to("/")]
    Index,
    #[not_found]
    NotFound,
}

fn switch<'a, G: Html>(ctx: Scope<'a>, route: &'a ReadSignal<AppRoutes>) -> View<G> {
    view! { ctx,
        div {
            (match route.get().as_ref() {
                AppRoutes::Index => view! { ctx,
                    index::Index()
                },
                AppRoutes::NotFound => view! { ctx,
                    "404 Not Found"
                },
            })
        }
    }
}

#[component]
pub fn App<G: Html>(ctx: Scope, pathname: Option<String>) -> View<G> {
    match pathname {
        Some(pathname) => {
            let route = AppRoutes::Index.match_path(&pathname);
            view! { ctx,
                StaticRouter(
                    view = switch,
                    route = route,
                )
            }
        }
        None => view! { ctx,
            Router(
                view = switch,
                integration = HistoryIntegration::new(),
            )
        },
    }
}
```

This leads to a bad hydration. However, replacing the `None` match arm in `App` to also use a `StaticRouter` produces a good result.

**Environment**

- Sycamore: master
- Browser: chrome
- OS: macOS

**Comment by danielalvsaaker** [comment]
This issue is caused by one or several changes done between beta.6 and beta.7.

**Comment by lukechu10** [comment]
Ah I know why. This was caused by https://github.com/sycamore-rs/sycamore/commit/a865f15d5aec851df5d8f9cb8aa055355006a37a because it added an extra component in the case of `Router` but not in `StaticRouter`.

I believe the proper fix to this would actually be to get rid of `StaticRouter` and instead create a `StaticIntegration` instead. In addition, this would make it more ergonomic for something like your case where you conditionally switch between `Router` and `StaticRouter`.

However, a dead-simple temporary work around would just be to create a (non `pub`) component (`StaticRouterBase`?) that is a clone of the `StaticRouter` and call that from `StaticRouter`.
