### ISSUE TITLE
Support for static rendering

### ISSUE THREAD

**Issue by philip-peterson** [sycamore-rs/sycamore#47]
**Is your feature request related to a problem? Please describe.**
There's a distinct lack of isomorphic support in the Rust ecosystem. I've been working on this for Yew, but it's such a large codebase (and userbase) that everything must tread very lightly and the code churn means it is a constantly moving target.

Less important, but, the ultimate context (admittedly somewhat personal) for this is that I would like to create an isomorphic app to replace the tangled mess that is [`main.js`](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/main.js) in the Rustdoc project, which will unlock incremental redesigns of the documentation platform we all use for Rust crate documentation. This could theoretically just be done with existing JS tooling, except that the build pipeline for crates.io is so complex and computationally expensive that they don't want an extra type of tooling added to the mix, so, whatever is added must be based in Rust.

**Describe the solution you'd like**
It would be a huge boon to this project if server-side rendering / isomorphic apps were supported from early on. Some things this encourages are: an opinionated app structure and ability to statically discover facts about the application (without running it) such as routes, which would probably be wanted at some point anyway. The first iteration of this feature would be just pure static rendering (aka SSR). The next step could be either isomorphic apps or static site generation, the latter being probably the least work since it's just an extension of static rendering. Once two of those things are done, the third should be relatively simple to add.

**Describe alternatives you've considered**
Percy and Yew are both solid contenders. I have been working on Yew for the past year, since it has more community support and is thus more proven, but again this is a complication due to inertia, and it would be cool to see a library support this use-case out of the box.

**Additional context**
I am also a maintainer of Trunk so I can provide support in the build process if there's any trickiness there.

**Questionnaire**
- [ ] I would like to implement this feature but I don't know where to start
- [ ] I would like to implement this feature and I have a solution
- [x] I don't have time to implement this / I don't want to implement this

**Comment by lukechu10** [comment]
Thanks for bringing this up. Definitely something I plan to support. Probably a good idea to great a working prototype of this early on to not have worries later.

**Comment by lights0123** [comment]
This will exist soon in #67.

**Comment by philip-peterson** [comment]
That's great news. If you need a server-side DOM for static rendering, although it's not really done yet, I've been working on https://github.com/philip-peterson/rust-rdom which is basically a Rust implementation of at least some of the WhatWG spec. I could use help if anyone's interested in collaborating.

**Comment by lukechu10** [comment]
There is a prototype of rendering `template!` to a string in #67. One problem we have now is related to API ergonomics. To support SSR and DOM, we need to compile a different version of the component depending on the context.

Since maple doesn't have a VDOM and doesn't plan to have one, an option would be to make `TemplateResult` generic, excepting a type param `G` which determines which backend to use (`DomNode` or `SsrNode`). Pros for this include more flexibility in which backends are used. We could render a `TemplateResult` to a string on the client as well if we wanted to. Cons mean that we would need to add a type param to every component.

The alternate route would be to use feature flags that determine which backend `TemplateResult` will use. This makes it slightly less flexible in that only one backend can be used at a time. However, I don't really see this as a problem because this use case would be extremely rare (in fact, I cannot think of a single use case where having multiple rendering backends would be useful and to my knowledge, most frameworks/libraries do not support this, e.g. svelte either compiles for `dom` or `ssr` but not both).
I do not think enabling this niche use case outweighs penalizing everybody else who doesn't need it.

However, there is a workaround for the first possibility. We could recommend creating a new type alias
```rust
type Template = TemplateResult<DomNode>
```
for users who don't need SSR. For those who do, they could add a cargo feature on _their_ crate (called `ssr`) and have the following code:
```rust
#[cfg(feature = "ssr")]
type Template = Template<SsrNode>;
#[cfg(not(feature = "ssr"))]
type Template = Template<DomNode>;
```
but then, we're back to the feature flag idea. Any opinions on this?

**Comment by fimbault** [comment]
Well, it could be useful to support both cases at runtime. See https://github.com/vercel/next.js/discussions/19606 as an example.

**Comment by lukechu10** [comment]
> Well, it could be useful to support both cases at runtime. See [vercel/next.js#19606](https://github.com/vercel/next.js/discussions/19606) as an example, or similar requirements (ex a serverless middleware in nextjs).

Yes that is how it works right now. If you look at https://maple-rs.netlify.app/basics/components, you'll see that in the next version, you need a `#[component]` attribute macro.

**Comment by arctic-hen7** [comment]
I feel it's worth mentioning that [Perseus](https://arctic-hen7/perseus) is a framework based on Sycamore that supports SSG fully, including using it with SSR (with state amalgamation).
