### ISSUE TITLE
Unable to view source in the docs: `Query parser error: "Unexpected `.`"`

### ISSUE THREAD

**Issue by kdheepak** [sycamore-rs/sycamore#671]
**Describe the bug**

I have a weird error when navigating in the docs. It was easiest to show the issue in a screen recording:

https://github.com/sycamore-rs/sycamore/assets/1813121/d9f747c8-1054-4867-8a1b-fbc549c68180

Clicking on `Source` in this page causes the issue: https://docs.rs/sycamore/latest/sycamore/reactive/struct.Signal.html

It seems to be linking from v0.8.2 to v0.8.1

**Comment by lukechu10** [comment]
This is unfortunately definitely a bug with `rustdoc` and there is really nothing we can do on our side except for publishing a new version so that `docs.rs` rebuilds the documentation.

Some alternatives right now:
- View the local documentation by running `cargo doc` in your project.
- Go to another version of `sycamore` on `docs.rs`.

In fact, the issue seems to have been fixed pretty quick by `rustdoc` already since the next (beta) version `0.9.0-beta.1` doesn't have this issue.
