### ISSUE TITLE
There should have a space between elements

### ISSUE THREAD

**Issue by liigo** [sycamore-rs/sycamore#757]
```
p {
    a(href="a.html") { "A" }
    a(href="b.html") { "B" }
}
```

it renders "AB" (no space).

VS

```html
<p>
    <a href="a.html">A</a>
    <a href="b.html">B</a>
</p>
```

it renders "A B" (has a space).

**Comment by lukechu10** [comment]
I think this is expected behavior. The HTML you have given is actually equivalent to `<a ...></a> <a ...></a>` (note the space) whereas the Sycamore view renders to `<a ...></a><a ...></a>`.

So there is an extra text node containing a single space in the HTML you’ve provided. If you want a space between the `<a>` tags, simply just put a `” “` after the first one.

**Comment by lukechu10** [comment]
I’m not actually sure what other frameworks do in this case but I suspect it’s something similar, so as to not introduce extra text nodes where they might be unexpected.

**Comment by liigo** [comment]
> `<a ...></a> <a ...></a>` (note the space)

the same as `a(){} a(){}`  (note the space). I'm using view! macro, not builder apis.

**Comment by lukechu10** [comment]
> > `<a ...></a> <a ...></a>` (note the space)
> 
> the same as `a(){} a(){}` (note the space). I'm using view! macro, not builder apis.

Yeah but the macro does not allow unquoted string literals because of limitations of proc-macros. The reason for this is because we don't know how much spaces there are between tokens so it would be impossible to create, say, a text node with `"hello   world"` as that would just become `"hello world"`.

What we're doing instead is forcing all text nodes to be in quotes. This also means that spaces between elements don't turn into text nodes. If you really want spacing between the elements, inserting an extra `" "` isn't that bad I don't think.

Another downside to automatically inserting spaces is that we would end up with a bunch of text nodes with spaces everywhere which could hurt performance from simply creating a bunch of extra text nodes. I looked at some other frameworks and both ReactJS and SolidJS have the same behavior, and I think for good reason.

I'm inclined to close this issue now unless other people have strong opinions about this.

**Comment by liigo** [comment]
> If you really want spacing between the elements, inserting an extra " " isn't that bad I don't think.

I'm OK with doing this. but... we're writing view!(...) *the-html-way*, but not gotten the-same-result, which makes confusing. Closing.
